### ISSUE TITLE
HPA docs for Rancher 2.6 is not available

### ISSUE THREAD

**Issue by stalin4suse** [rancher/rancher-docs#28] opened 2022-09-12 10:37 UTC
# Rancher 2.6 does not have HPA doc page updated. 

To navigate to that page, you can click on `How-to Guides` --> `New User Guides` --> `Kubernetes Resources Setup` --> `Horizontal Pod Autoscaler`

You can also click on this [link](https://docs.ranchermanager.rancher.io/pages-for-subheaders/horizontal-pod-autoscaler) which takes you to that page.

**Comment by btat** [comment] 2022-09-12 15:02
Closing as duplicate of #26.

**Closed by btat** 2022-09-12 15:02 UTC
Labels: duplicate
