### ISSUE TITLE
Add Cloud Marketplace Integration - Azure Marketplace Integration

### ISSUE THREAD

**Issue by tlssuse** [rancher/rancher-docs#987] opened 2023-11-15 22:26 UTC
## Summary
Now that Rancher Prime is available in the Microsoft Azure Marketplace, update the documentation to reflect this.

## Details
1. Update "This integration only supports AWS" to "This integration supports Amazon Web Services and Microsoft Azure." on https://ranchermanager.docs.rancher.com/pages-for-subheaders/cloud-marketplace
2. Add an equivalent for Azure of the subsection, https://ranchermanager.docs.rancher.com/pages-for-subheaders/aws-cloud-marketplace

**Comment by btat** [comment] 2023-11-16 19:08
Possible duplicate of https://github.com/rancher/rancher-docs/issues/987. @LucasSaintarbor to confirm.

**Comment by tlssuse** [comment] 2023-11-16 19:24
@btat & @LucasSaintarbor : This does indeed appear to be a duplicate of #917.  Thank you for identifying it.  Feel welcome to close this issue.

**Comment by btat** [comment] 2023-11-16 19:31
Thank you for the confirmation.

**Closed by btat** 2023-11-16 19:31 UTC
